"""
Experience extraction rules shared by CV and job preprocessing notebooks.

Use numeric year/month extraction first, then these keyword rules as fallback
when the text does not contain an explicit experience duration.

Level mapping from years:
    < 1 year      → intern
    1 to < 2      → junior
    2 to < 5      → mid
    5+            → senior
    no info       → unknown
"""

EXPERIENCE_LEVEL_RANGES = {
    "intern": {"min_years": 0, "max_years": 1, "include_max": False},
    "junior": {"min_years": 1, "max_years": 2, "include_max": False},
    "mid": {"min_years": 2, "max_years": 5, "include_max": False},
    "senior": {"min_years": 5, "max_years": None, "include_max": True},
}

EXPERIENCE_RULES = {
    "intern": {
        "years": 0.0,
        "keywords": [
            "intern",
            "interns",
            "trainees",
            "internship",
            "internships",
            "trainee",
            "graduate trainee",
            "graduates",
            "graduate trainees",
            "management trainee",
            "industrial trainee",
            "industrial training",
            "apprentice",
            "apprenticeship",
            "fresher",
            "freshers",
            "fresh graduate",
            "recent graduate",
            "new graduate",
            "school leaver",
            "school leavers",
            "entry level",
            "entry-level",
            "undergraduate",
            "undergraduate trainee",
            "final year student",
            "no experience",
            "no work experience",
            "no formal experience",
            "no prior experience",
            "zero experience",
            "0 years",
            "0 year",
            "less than 1 year",
            "less than one year",
            "experience not required",
            "without experience",
        ],
    },
    "junior": {
        "years": 1.0,
        "keywords": [
            "junior",
            "juniors",
            "jr",
            "associate",
            "assistant",
            "entry junior",
            "early career",
            "junior level",
            "junior-level",
            "1 year",
            "1+ year",
            "1+ years",
            "1-2 years",
            "1–2 years",
            "1 to 2 years",
            "one year",
            "less than 2 years",
            "below 2 years",
            "minimum 1 year",
            "at least 1 year",
        ],
    },
    "mid": {
        "years": 3.0,
        "keywords": [
            "mid level",
            "mid-level",
            "intermediate",
            "mid-senior",
            "assistant manager",
            "deputy manager",
            "2 years",
            "2+ years",
            "3 years",
            "3+ years",
            "4 years",
            "4+ years",
            "2-4 years",
            "2–4 years",
            "2-3 years",
            "2–3 years",
            "3-4 years",
            "3–4 years",
            "3-5 years",
            "2 to 4 years",
            "3 to 5 years",
            "minimum 2 years",
            "minimum 3 years",
            "minimum 4 years",
            "at least 2 years",
            "at least 3 years",
            "at least 4 years",
            "two years",
            "three years",
            "four years",
        ],
    },
    "senior": {
        "years": 5.0,
        "keywords": [
            "senior",
            "seniors",
            "executive",
            "senior executive",
            "senior manager",
            "senior supervisor",
            "senior director",
            "senior architect",
            "executives",
            "sr",
            "senior level",
            "senior-level",
            "senior manager",
            "general manager",
            "lead",
            "leads",
            "team lead",
            "team leaders",
            "tech lead",
            "lead engineer",
            "lead developer",
            "principal",
            "principal engineer",
            "staff engineer",
            "chief",
            "architect",
            "head",
            "head of",
            "director",
            "supervisor",
            "senior manager",
            "vp",
            "vice president",
            "5 years",
            "5+ years",
            "6 years",
            "6+ years",
            "7 years",
            "8 years",
            "9 years",
            "10 years",
            "10+ years",
            "12 years",
            "15 years",
            "5-8 years",
            "5–8 years",
            "5-10 years",
            "5–10 years",
            "6-8 years",
            "8+ years",
            "minimum 5 years",
            "at least 5 years",
            "five years",
        ],
    },
}